"""Rename column in resume_file table

Revision ID: 105a3319e41e
Revises: efe60281e8b1
Create Date: 2023-08-10 04:53:50.962502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '105a3319e41e'
down_revision: Union[str, None] = 'efe60281e8b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resume_file', sa.Column('file_path', sa.String(), nullable=False))
    op.drop_column('resume_file', 'temp')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resume_file', sa.Column('temp', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('resume_file', 'file_path')
    # ### end Alembic commands ###
