"""Test

Revision ID: f99830877912
Revises: 5c934a1e5253
Create Date: 2023-08-12 01:31:50.310486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f99830877912'
down_revision: Union[str, None] = '5c934a1e5253'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resume', sa.Column('education', sa.Enum('postgraduate_study', 'magistracy', 'specialty', 'higher', 'bachelor_course', 'bachelor', 'average_first', 'average_second', 'average_general', 'basic_general', 'none', name='education'), nullable=False))
    op.add_column('resume', sa.Column('experience', sa.Integer(), nullable=False))
    op.add_column('resume', sa.Column('profession', sa.ARRAY(sa.String()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resume', 'profession')
    op.drop_column('resume', 'experience')
    op.drop_column('resume', 'education')
    # ### end Alembic commands ###
