"""Rename column in resume_file table

Revision ID: 6a8a7a1b924e
Revises: 105a3319e41e
Create Date: 2023-08-10 04:54:41.473536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a8a7a1b924e'
down_revision: Union[str, None] = '105a3319e41e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resume_file', sa.Column('file_name', sa.String(), nullable=False))
    op.drop_column('resume_file', 'file_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resume_file', sa.Column('file_path', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('resume_file', 'file_name')
    # ### end Alembic commands ###
